import React from "react";

export default function Options() {
  return (
    <div className="options">
      <datalist id="datalistOptions">
        <option value="Abidjan" />
        <option value="Abu Dhabi" />
        <option value="Abuja" />
        <option value="Accra" />
        <option value="Addis Ababa" />
        <option value="Ahmedabad" />
        <option value="Aleppo" />
        <option value="Alexandria" />
        <option value="Algiers" />
        <option value="Almaty" />
        <option value="Amman" />
        <option value="Amsterdam" />
        <option value="Anchorage" />
        <option value="Andorra la Vella" />
        <option value="Ankara" />
        <option value="Antananarivo" />
        <option value="Apia" />
        <option value="Arnold" />
        <option value="Ashgabat" />
        <option value="Asmara" />
        <option value="Asuncion" />
        <option value="Athens" />
        <option value="Auckland" />
        <option value="Avarua" />
        <option value="Baghdad" />
        <option value="Baku" />
        <option value="Bamako" />
        <option value="Banda Aceh" />
        <option value="Bandar Seri Begawan" />
        <option value="Bandung" />
        <option value="Bangkok" />
        <option value="Bangui" />
        <option value="Banjul" />
        <option value="Barcelona" />
        <option value="Barranquilla" />
        <option value="Basrah" />
        <option value="Basrah" />
        <option value="Basse-Terre" />
        <option value="Basseterre" />
        <option value="Beijing" />
        <option value="Beirut" />
        <option value="Belem" />
        <option value="Belgrade" />
        <option value="Belo Horizonte" />
        <option value="Bengaluru" />
        <option value="Berlin" />
        <option value="Bern" />
        <option value="Bishkek" />
        <option value="Bissau" />
        <option value="Bogota" />
        <option value="Brasilia" />
        <option value="Bratislava" />
        <option value="Brazzaville" />
        <option value="Bridgetown" />
        <option value="Brisbane" />
        <option value="Brussels" />
        <option value="Bucharest" />
        <option value="Budapest" />
        <option value="Buenos Aires" />
        <option value="Bujumbura" />
        <option value="Bursa" />
        <option value="Busan" />
        <option value="Cairo" />
        <option value="Cali" />
        <option value="Caloocan" />
        <option value="Camayenne" />
        <option value="Canberra" />
        <option value="Cape Town" />
        <option value="Caracas" />
        <option value="Casablanca" />
        <option value="Castries" />
        <option value="Charlotte Amalie" />
        <option value="Chengdu" />
        <option value="Chennai" />
        <option value="Chicago" />
        <option value="Colombo" />
        <option value="Conakry" />
        <option value="Copenhagen" />
        <option value="Cordoba" />
        <option value="Daejeon" />
        <option value="Dakar" />
        <option value="Dallas" />
        <option value="Damascus" />
        <option value="Dar es Salaam" />
        <option value="Delhi" />
        <option value="Denver" />
        <option value="Djibouti" />
        <option value="Dodoma" />
        <option value="Doha" />
        <option value="Douala" />
        <option value="Dubai" />
        <option value="Dublin" />
        <option value="Durban" />
        <option value="Faisalabad" />
        <option value="Fort-de-France" />
        <option value="Freetown" />
        <option value="Funafuti" />
        <option value="Gaborone" />
        <option value="George Town" />
        <option value="Gitega" />
        <option value="Giza" />
        <option value="Guadalajara" />
        <option value="Guangzhou" />
        <option value="Guatemala City" />
        <option value="Gwangju" />
        <option value="Hamburg" />
        <option value="Hanoi" />
        <option value="Harare" />
        <option value="Havana" />
        <option value="Helsinki" />
        <option value="Hong Kong" />
        <option value="Honolulu" />
        <option value="Houston" />
        <option value="Hyderabad" />
        <option value="Ibadan" />
        <option value="Incheon" />
        <option value="Istanbul" />
        <option value="Izmir" />
        <option value="Jaipur" />
        <option value="Jeddah" />
        <option value="Jerusalem" />
        <option value="Johannesburg" />
        <option value="Juarez" />
        <option value="Juba" />
        <option value="Kabul" />
        <option value="Kaduna" />
        <option value="Kampala" />
        <option value="Kano" />
        <option value="Kanpur" />
        <option value="Kawasaki" />
        <option value="Kharkiv" />
        <option value="Khartoum" />
        <option value="Khulna" />
        <option value="Kigali" />
        <option value="Kingsburg" />
        <option value="Kingston" />
        <option value="Kingstown" />
        <option value="Kinshasa" />
        <option value="Kobe" />
        <option value="Kumasi" />
        <option value="Kuwait" />
        <option value="Kyiv" />
        <option value="Kyoto" />
        <option value="La Paz" />
        <option value="Lagos" />
        <option value="Lahore" />
        <option value="Libreville" />
        <option value="Lilongwe" />
        <option value="Lima" />
        <option value="Lisbon" />
        <option value="Lome" />
        <option value="London" />
        <option value="Los Angeles" />
        <option value="Luanda" />
        <option value="Lubumbashi" />
        <option value="Lusaka" />
        <option value="Luxembourg" />
        <option value="Macau" />
        <option value="Madrid" />
        <option value="Malabo" />
        <option value="Male" />
        <option value="Manama" />
        <option value="Manila" />
        <option value="Maputo" />
        <option value="Maracay" />
        <option value="Marigot" />
        <option value="Maseru" />
        <option value="Mashhad" />
        <option value="Mecca" />
        <option value="Medan" />
        <option value="Medellin" />
        <option value="Medina" />
        <option value="Melbourne" />
        <option value="Mexico City" />
        <option value="Miami" />
        <option value="Minsk" />
        <option value="Mogadishu" />
        <option value="Monaco" />
        <option value="Monrovia" />
        <option value="Montevideo" />
        <option value="Montreal" />
        <option value="Moroni" />
        <option value="Moscow" />
        <option value="Mosul" />
        <option value="Mumbai" />
        <option value="N'Djamena" />
        <option value="Nairobi" />
        <option value="Nanjing" />
        <option value="Nassau" />
        <option value="New York" />
        <option value="Niamey" />
        <option value="Nicosia" />
        <option value="Nuku'alofa" />
        <option value="Oranjestad" />
        <option value="Oslo" />
        <option value="Ottawa" />
        <option value="Ouagadougou" />
        <option value="Palembang" />
        <option value="Panama" />
        <option value="Paris" />
        <option value="Perth" />
        <option value="Philadelphia" />
        <option value="Phoenix" />
        <option value="Podgorica" />
        <option value="Port Louis" />
        <option value="Port Moresby" />
        <option value="Porto-Novo" />
        <option value="Praia" />
        <option value="Pretoria" />
        <option value="Pune" />
        <option value="Quezon City" />
        <option value="Quito" />
        <option value="Rabat" />
        <option value="Recife" />
        <option value="Rio de Janeiro" />
        <option value="Rome" />
        <option value="Roseau" />
        <option value="Saint Helier" />
        <option value="Saint-Pierre" />
        <option value="Salvador" />
        <option value="San Antonio" />
        <option value="San Diego" />
        <option value="San Francisco" />
        <option value="San Jose" />
        <option value="San Salvador" />
        <option value="Santiago" />
        <option value="Sao Paulo" />
        <option value="Seattle" />
        <option value="Seoul" />
        <option value="Shanghai" />
        <option value="Sharjah" />
        <option value="Shenzhen" />
        <option value="Singapore" />
        <option value="Sofia" />
        <option value="Soweto" />
        <option value="Stockholm" />
        <option value="Surat" />
        <option value="Sydney" />
        <option value="Tabriz" />
        <option value="Taipei" />
        <option value="Tarawa" />
        <option value="Tel Aviv" />
        <option value="Tokyo" />
        <option value="Toronto" />
        <option value="Torshavn" />
        <option value="Tripoli" />
        <option value="Tunis" />
        <option value="Ulan Bator" />
        <option value="Valencia" />
        <option value="Vancouver" />
        <option value="Victoria" />
        <option value="Vienna" />
        <option value="Vientiane" />
        <option value="Warsaw" />
        <option value="Washington" />
        <option value="Wellington" />
        <option value="Windhoek" />
        <option value="Wuhan" />
        <option value="Xi'an" />
        <option value="Yamoussoukro" />
        <option value="Yangon" />
        <option value="Yaounde" />
        <option value="Yekaterinburg" />
        <option value="Yokohama" />
        <option value="Zagreb" />
      </datalist>
    </div>
  );
}
